if(EXISTS "/mnt/d/Projects/BreadTerminal/build-linux/tests/termcore_tests[1]_tests.cmake")
  include("/mnt/d/Projects/BreadTerminal/build-linux/tests/termcore_tests[1]_tests.cmake")
else()
  add_test(termcore_tests_NOT_BUILT termcore_tests_NOT_BUILT)
endif()
